[workspace]
channels = ["robostack-jazzy","conda-forge"]
name = "WGS"
platforms = ["win-64"]
version = "0.1.0"

[tasks]
# 创建一个名为 vs-shell 的任务
vs-shell = 'cmd /k "call "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvarsall.bat" x64 && pixi shell"'

[dependencies]
cxx-compiler = ">=1.11.0,<2"
cmake = ">=4.1.2,<5"
ninja = ">=1.13.1,<2"
colcon-common-extensions = ">=0.3.0,<0.4"
qt6-main = ">=6.9.3,<7"
ros-jazzy-desktop = ">=0.11.0,<0.12"
ros-jazzy-turtlesim = ">=1.8.3,<2"
setuptools = ">=80.9.0,<81"
